export enum ItemStatus {
    PENDING_APPROVAL = "PENDING_APPROVAL",
    AVAILABLE = "AVAILABLE",
    REJECTED = "REJECTED",
    RENTED_PENDING_CONFIRM = "RENTED_PENDING_CONFIRM",
    RENTED = "RENTED",
    RETURN_PENDING_CHECK = "RETURN_PENDING_CHECK",
    BANNED = "BANNED",
    DELETED = "DELETED",
    MISSING = "MISSING",
}
