package org.camphub.be_camphub.enums;

public enum BookingStatus {
    PENDING_CONFIRM,
    PAID_REJECTED,
    WAITING_DELIVERY,
    IN_USE,
    DUE_FOR_RETURN,
    RETURNED_PENDING_CHECK,
    RETURN_REFUND_REQUESTED,
    RETURN_REFUND_PROCESSING,
    WAITING_REFUND,
    COMPLETED,
    DISPUTE_PENDING_REVIEW,
    COMPENSATION_COMPLETED,
    LATE_RETURN,
    OVERDUE,
    DAMAGED_ITEM,
    FORFEITED,
}
